name: "Build Win app"
description: "Builds the application with Qt on various platforms"
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          allow-prereleases: false

      - name: Verify Python version
        shell: cmd
        run: python --version

      - name: Setup Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          modules: qtbase qttools qtdeclarative
          host: windows
          target: desktop
          setup-python: false

      - name: Set up MSVC environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build
        shell: cmd
        run: |
          qmake
          nmake
      - uses: actions/upload-artifact@v4
        with:
          name: qml-parser-windows
          path: dist\qml-parser.exe
