name: "Build Win app"
description: "Builds the application with Qt on various platforms"
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          modules: qtbase qttools qtdeclarative
          host: windows
          target: desktop
      - name: Build
        shell: cmd
        run: |
          qmake CONFIG+=release
          nmake
      - uses: actions/upload-artifact@v4
        with:
          name: qml-parser-windows
          path: dist\qml-parser.exe
