name: "Build Win app"
description: "Builds the application with Qt on various platforms"
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          allow-prereleases: false

      - name: Setup Visual Studio 2022
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          modules: qtbase qttools qtdeclarative
          host: windows
          target: desktop
          setup-python: false

      - name: Configure environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set PATH=%PATH%;C:\Qt\Tools\QtCreator\bin

      - name: Set up MSVC environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build
        shell: cmd
        run: |
          qmake
          nmake
          windeployqt dist\qml-parser.exe --no-compiler-runtime --no-translations -no-plugins -verbose=1
      - uses: actions/upload-artifact@v4
        with:
          name: qml-parser-windows
          path: dist\
